
version: '3.9'

services:
  db:
    image: postgres:15
    container_name: library_db
    restart: always
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: library_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build:
      context: ./backend
    container_name: library_app
    volumes:
      - ./backend:/app  # Mount local code into container
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://dev_user:12345678@db:5432/library_db

volumes:
  db_data:
